Sources/Player.swift
Hi,
I want to embed Player in ContainerView of Storyboard!
=> Add init methods for Storyboard

Sources/Player.swift
It should only start playing if user paused it.
=> Disable playing on stop state.

Player.podspec, Project/Player/ViewController.swift, Project/PlayerTV/ViewController.swift, Sources/Player.swift
This solves #51, even though it was already answered on StackOverflow.
=> Adding a delegate method for receiving current playtime updates

Sources/Player.swift
Added timeObserver property, and removed time observer from player on deinit
=> Fix for #77

Project/Player.xcodeproj/project.pbxproj, Project/PlayerTV/AppDelegate.swift, Project/PlayerTV/ViewController.swift, Sources/Player.swift
Fixed compatibility with Swift 3 (Xcode 8 beta 3).
Added compatibility with Swift 3 for tvOS project.
Closes #87.
=> Swift 3 (Xcode 8 beta 3) (bis)

Sources/Player.swift
=> Variable buffer size

Player.podspec, Sources/Player.swift
Solves https://github.com/piemonte/Player/issues/109
=> make PlayerDelegate methods optional

Sources/Player.swift
fix #117
I had to remove the extension so the methods can be overridden, but I left the pragma mark.
=> Opening Player properties

Project/Player/ViewController.swift, Sources/Player.swift
=> Fix: Setting url before viewDidLoad

Sources/Player.swift
Add seek method with completion handler to make some changes after seek to specific time
=> Add seek method with completion handler

Project/Player/ViewController.swift, Project/PlayerTV/ViewController.swift
=> Fix demo crash at start

Project/Player/ViewController.swift, Project/PlayerTV/ViewController.swift, Sources/Player.swift
Adds an enhancement for #64 to give a delegate callback when the buffer time changes
=> #64 buffer video support

Sources/Player.swift
An alternative to having to import AVKit would be to simply provide access to the playerLayer
=> provides access to picture and picture support for users of library

Sources/Player.swift
=> Allow setting up Player from local AVAsset

README.md
=> Update README.md for latest version

Sources/Player.swift
Hello😸
I fixed Issue #170 by reference to https://stackoverflow.com/questions/10433774/avurlasset-getting-video-size
Please review🙇
=> Fix issue#170 Player'naturalSize doesn't match the actual video size

Sources/Player.swift
This callback can be really helpful for debugging.
=> Add error handling to delegate

Sources/Player.swift
=> Fix for looping issue

Sources/Player.swift
Looks like this part can be removed. This commented code not used. 🧹✨
=> Remove code

Sources/Player.swift
Needed this for a project and I presume it might be useful for others
=> Expose AVPlayer rate
